---
- name: Chapter1 Testing Playbooks
  hosts: all

  tasks:
  - name: Testing connectivity
    ping:
  - name: Install other packages
    yum: 
      name: "{{item}}"
      state: present
    with_items:
           - mongodb
           - tomcat
           - gedit
