---
- name: Installing WordPress
  hosts: web1
  become: yes

  tasks:
  - name: Installing PHP
    yum:
      name: php
      state: present
  - name: Install supporting php packages
    yum:
      name: "{{item}}"
    with_items:
        - php
        - php-fpm
        - php-mysql
        - php-xml
  - name: Install mariadb
    yum:
      name: mariadb
      state: present
  - name: Install supporting packages for mariadb
    yum:
      name: MySQL-python
      state: present

  - name: Generate new root password for mariadb
    command: openssl rand -hex 7
    register: mariadb_new_root_pass

#  - name: Remove anonymous users from mariadb
 #   mysql_user: 
  #        name: ""
      #    state: absent
  #- name: Remove test database
   # mysql_db:
    #     name: test
     #    state: absent
   - name: Update mariadb root password
     mysql_user:
           name: root
           host: "{{item}}"
           password: "{{mariadb_new_root_pass.stdout}}"
     with_items:
         - "{{ansible_hostname}}"      
         - 127.0.0.1
         - ::1
         - localhost

    - name: Output new root password
      debug:
         msg: "New root password is {{mariadb_new_root_pass.stdout}}"