---
- name: Installing WordPress
  hosts: web1
  become: yes

  tasks:
  - name: Installing PHP
    yum:
      name: php
      state: present
  - name: Install supporting php packages
    yum:
      name: "{{item}}"
    with_items:
        - php
        - php-fpm
        - php-mysql
        - php-xml