---
- name: Chapter1 Testing Playbooks
  hosts: all
  become: yes

  tasks:
  - name: Install other packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
           - mlocate
           - wget
           - gedit
           - mongodb
    changed_when: false

