---
# tasks file for gchongong.php
- name: Installing PHP
  yum:
    name: php
    state: present
- name: Install supporting php packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
        - php
        - php-fpm
        - php-mysql
        - php-xml

- name: Install elinks
  yum:
    name: elinks
    state: present
